program SqlQueryBuilderTestProject;
{

  DUnit Test Project generated by dtest

}

{$IFDEF CONSOLE_TESTRUNNER}
{$APPTYPE CONSOLE}
{$ENDIF}

uses
  Forms,
  TestFramework,
  GUITestRunner,
  TextTestRunner,
  XMLTestRunner,
  SqlQueryBuilderTestSuite in 'SqlQueryBuilderTestSuite.pas',
  SqlQueryBuilder in '..\src\SqlQueryBuilder.pas',
  SqlWhereClauseBuilder in '..\src\SqlWhereClauseBuilder.pas';

begin
  Application.Initialize;
  if IsConsole then
    TextTestRunner.RunRegisteredTests
  else
    GUITestRunner.RunRegisteredTests;
end.